SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET default_tablespace = '';
SET default_with_oids = false;

ALTER TABLE products ADD COLUMN supplier_id INTEGER;
UPDATE products SET supplier_id = 1 WHERE product_name IN ('Chang', 'Aniseed Syrup');
UPDATE products SET supplier_id = 2 WHERE product_name IN ('Chef Anton''s Cajun Seasoning', 'Chef Anton''s Gumbo Mix', 'Louisiana Fiery Hot Pepper Sauce', 'Louisiana Hot Spiced Okra');
UPDATE products SET supplier_id = 3 WHERE product_name IN ('Grandma''s Boysenberry Spread', 'Uncle Bob''s Organic Dried Pears', 'Northwoods Cranberry Sauce');
UPDATE products SET supplier_id = 4 WHERE product_name IN ('Mishi Kobe Niku', 'Ikura', 'Longlife Tofu');
UPDATE products SET supplier_id = 5 WHERE product_name IN ('Queso Cabrales', 'Queso Manchego La Pastora');
UPDATE products SET supplier_id = 6 WHERE product_name IN ('Konbu', 'Tofu', 'Genen Shouyu');
UPDATE products SET supplier_id = 7 WHERE product_name IN ('Pavlova', 'Alice Mutton', 'Carnarvon Tigers', 'Vegie-spread', 'Outback Lager');
UPDATE products SET supplier_id = 8 WHERE product_name IN ('Chai', 'Teatime Chocolate Biscuits', 'Sir Rodney''s Marmalade', 'Sir Rodney''s Scones', 'Scottish Longbreads');
UPDATE products SET supplier_id = 9 WHERE product_name IN ('Gustaf''s Knäckebröd', 'Tunnbröd');
UPDATE products SET supplier_id = 10 WHERE product_name IN ('Guaraná Fantástica');
UPDATE products SET supplier_id = 11 WHERE product_name IN ('NuNuCa Nuß-Nougat-Creme', 'Gumbär Gummibärchen', 'Schoggi Schokolade');
UPDATE products SET supplier_id = 12 WHERE product_name IN ('Rössle Sauerkraut', 'Thüringer Rostbratwurst', 'Wimmers gute Semmelknödel', 'Rhönbräu Klosterbier', 'Original Frankfurter grüne Soße');
UPDATE products SET supplier_id = 13 WHERE product_name IN ('Nord-Ost Matjeshering');
UPDATE products SET supplier_id = 14 WHERE product_name IN ('Gorgonzola Telino', 'Mascarpone Fabioli', 'Mozzarella di Giovanni');
UPDATE products SET supplier_id = 15 WHERE product_name IN ('Geitost', 'Gudbrandsdalsost', 'Flotemysost');
UPDATE products SET supplier_id = 16 WHERE product_name IN ('Sasquatch Ale', 'Steeleye Stout', 'Laughing Lumberjack Lager');
UPDATE products SET supplier_id = 17 WHERE product_name IN ('Inlagd Sill', 'Gravad lax', 'Röd Kaviar');
UPDATE products SET supplier_id = 18 WHERE product_name IN ('Côte de Blaye', 'Chartreuse verte');
UPDATE products SET supplier_id = 19 WHERE product_name IN ('Boston Crab Meat', 'Jack''s New England Clam Chowder');
UPDATE products SET supplier_id = 20 WHERE product_name IN ('Singaporean Hokkien Fried Mee', 'Ipoh Coffee', 'Gula Malacca');
UPDATE products SET supplier_id = 21 WHERE product_name IN ('Rogede sild', 'Spegesild');
UPDATE products SET supplier_id = 22 WHERE product_name IN ('Zaanse koeken', 'Chocolade');
UPDATE products SET supplier_id = 23 WHERE product_name IN ('Maxilaku', 'Valkoinen suklaa', 'Lakkalikööri');
UPDATE products SET supplier_id = 24 WHERE product_name IN ('Manjimup Dried Apples', 'Filo Mix', 'Perth Pasties');
UPDATE products SET supplier_id = 25 WHERE product_name IN ('Tourtière', 'Pâté chinois');
UPDATE products SET supplier_id = 26 WHERE product_name IN ('Gnocchi di nonna Alice', 'Ravioli Angelo');
UPDATE products SET supplier_id = 27 WHERE product_name IN ('Escargots de Bourgogne');
UPDATE products SET supplier_id = 28 WHERE product_name IN ('Raclette Courdavault', 'Camembert Pierrot');
UPDATE products SET supplier_id = 29 WHERE product_name IN ('Sirop d''érable', 'Tarte au sucre');

ALTER TABLE products ADD FOREIGN KEY (supplier_id) REFERENCES suppliers(id_supplier);
